from typing import Dict
from shared.llm_manager import LLMManager

class DeveloperAgent:
    """
    Senior Software Engineer Agent - Implements features following TDD and best practices
    
    Coding standards:
    
    Python:
    - Use type hints for all function signatures
    - Follow PEP 8 style guidelines
    - Write pytest tests with clear arrange-act-assert structure
    - Use async/await for I/O operations
    - Document functions with docstrings
    
    TypeScript/Node.js:
    - Use strict TypeScript configuration
    - Follow functional programming patterns where appropriate
    - Write Jest tests with comprehensive coverage
    - Use pnpm for package management
    - Implement proper error handling
    
    Testing Requirements:
    - Write tests BEFORE implementation (TDD)
    - Minimum 80% code coverage
    - Include unit, integration, and E2E tests
    - Use Cucumber for BDD scenarios when needed
    
    API Development:
    - Test all endpoints with Postman collections
    - Document APIs with OpenAPI/Swagger
    - Implement proper authentication and authorization
    - Follow RESTful design principles
    """
    
    def __init__(self, llm_config: Dict):
        self.llm_config = llm_config
        self.llm = LLMManager()
        print("💻 Senior Software Engineer Agent initialized")
    
    def implement_feature(self, requirements: Dict, guidelines: Dict) -> Dict:
        """Implements feature using LLM code generation"""
        print(f"\n⚙️  Implementing: {requirements.get('title', 'Feature')}")
        
        # Generate implementation with LLM
        code_prompt = f"""Generate Python code for:

Requirements:
{requirements.get('title')}
{requirements.get('description')}

Guidelines:
- {guidelines.get('code_style')}
- {guidelines.get('security')}
- Include error handling
- Add type hints

Generate complete, production-ready code."""

        try:
            generated_code = self.llm.generate_code(code_prompt, language="python")
            print(f"   🤖 Code generated by LLM")
        except:
            generated_code = f"# Implementation for {requirements.get('ticket_id')}\n# TODO: Implement manually\n"
            print(f"   ⚠️  LLM unavailable, created stub")
        
        # Generate tests
        test_prompt = f"""Generate pytest unit tests for:

{requirements.get('title')}

Include:
- Happy path test
- Error case test
- Edge cases"""

        try:
            generated_tests = self.llm.generate_code(test_prompt, language="python")
            print(f"   🤖 Tests generated by LLM")
        except:
            generated_tests = f"# Tests for {requirements.get('ticket_id')}\n# TODO: Implement tests\n"
            print(f"   ⚠️  LLM unavailable, created test stub")
        
        implementation = {
            "status": "completed",
            "code": generated_code,
            "tests": generated_tests,
            "documentation": f"# Documentation for {requirements.get('ticket_id')}\n"
        }
        
        print(f"   ✅ Implementation completed")
        
        # Save to file for Copilot review
        self._save_for_copilot_review(requirements, implementation)
        
        return implementation
    
    def _save_for_copilot_review(self, requirements: Dict, implementation: Dict):
        """Save generated code for manual review with GitHub Copilot"""
        ticket_id = requirements.get('ticket_id', 'unknown')
        output_dir = f"./generated_code/{ticket_id}"
        
        import os
        os.makedirs(output_dir, exist_ok=True)
        
        # Save implementation
        with open(f"{output_dir}/implementation.py", 'w') as f:
            f.write(implementation['code'])
        
        # Save tests
        with open(f"{output_dir}/test_implementation.py", 'w') as f:
            f.write(implementation['tests'])
        
        print(f"   💾 Saved to {output_dir}/ for Copilot review")
